baseURL = 'https://dzakyputra.com/'
languageCode = 'en-us'
title = 'Dzaky Widya Putra'
pagination.pagerSize = 3
publishDir = 'docs'
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "A blog for documenting my life"
  author = 'Dzaky Widya Putra'
  items = 10

[menu]
 [[menu.main]]
   identifier = "posts"
   name = "Posts"
   url = "/posts/"
   weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[params.google.analytics]
  id = "G-0ZNR6ZW0MM"

ignoreErrors = ["error-remote-getjson"]
